//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.01 at 01:18:12 PM CEST 
//


package platform.service_one.configuration.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import platform.service.configuration.schema.TConfigurationBase;


/**
 * <p>Java class for t_adminServiceConfigurationBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_adminServiceConfigurationBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://platform/service/configuration/}t_configurationBase">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_adminServiceConfigurationBase")
@XmlSeeAlso({
    TAdminServiceConfiguration100 .class
})
public class TAdminServiceConfigurationBase100
    extends TConfigurationBase
{


}
