//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.17 at 06:57:47 PM CEST 
//


package platform.service.configuration.schema;

import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the platform.service.configuration.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: platform.service.configuration.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TServiceConfiguration }
     * 
     */
    public TServiceConfiguration createTServiceConfiguration() {
        return new TServiceConfiguration();
    }

    /**
     * Create an instance of {@link TServiceConfiguration.Platform }
     * 
     */
    public TServiceConfiguration.Platform createTServiceConfigurationPlatform() {
        return new TServiceConfiguration.Platform();
    }

    /**
     * Create an instance of {@link TConfigurationBase }
     * 
     */
    public TConfigurationBase createTConfigurationBase() {
        return new TConfigurationBase();
    }

    /**
     * Create an instance of {@link TServiceConfiguration.Service }
     * 
     */
    public TServiceConfiguration.Service createTServiceConfigurationService() {
        return new TServiceConfiguration.Service();
    }

    /**
     * Create an instance of {@link TServiceConfiguration.Platform.SDContext }
     * 
     */
    public TServiceConfiguration.Platform.SDContext createTServiceConfigurationPlatformSDContext() {
        return new TServiceConfiguration.Platform.SDContext();
    }

    /**
     * Create an instance of {@link TServiceConfiguration.Platform.Domain }
     * 
     */
    public TServiceConfiguration.Platform.Domain createTServiceConfigurationPlatformDomain() {
        return new TServiceConfiguration.Platform.Domain();
    }

    /**
     * Create an instance of {@link ServiceConfiguration }}
     * 
     */
    @XmlElementDecl(namespace = "http://platform/service/configuration/", name = "serviceConfiguration")
    public ServiceConfiguration createServiceConfiguration(TServiceConfiguration value) {
        return new ServiceConfiguration(value);
    }

    /**
     * Create an instance of {@link Configuration }}
     * 
     */
    @XmlElementDecl(namespace = "http://platform/service/configuration/", name = "configuration")
    public Configuration createConfiguration(TConfigurationBase value) {
        return new Configuration(value);
    }

}
