//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.01 at 01:18:33 PM CEST 
//


package platform.service_two.configuration.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class AdminServiceConfiguration100
    extends JAXBElement<TAdminServiceConfiguration100>
{

    protected final static QName NAME = new QName("http://admin/service/configuration/v2.0.0/", "adminServiceConfiguration");

    public AdminServiceConfiguration100(TAdminServiceConfiguration100 value) {
        super(NAME, ((Class) TAdminServiceConfiguration100 .class), null, value);
    }

    public AdminServiceConfiguration100() {
        super(NAME, ((Class) TAdminServiceConfiguration100 .class), null, null);
    }

}
