//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.01 at 01:18:33 PM CEST 
//


package platform.service_two.configuration.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_adminServiceConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_adminServiceConfiguration">
 *   &lt;complexContent>
 *     &lt;extension base="{http://admin/service/configuration/v2.0.0/}t_adminServiceConfigurationBase">
 *       &lt;sequence>
 *         &lt;element name="admin_service_specific_element">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="admin_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_adminServiceConfiguration", propOrder = {
    "adminServiceSpecificElement"
})
public class TAdminServiceConfiguration100
    extends TAdminServiceConfigurationBase100
{

    @XmlElement(name = "admin_service_specific_element", required = true)
    protected TAdminServiceConfiguration100 .AdminServiceSpecificElement adminServiceSpecificElement;

    /**
     * Gets the value of the adminServiceSpecificElement property.
     * 
     * @return
     *     possible object is
     *     {@link TAdminServiceConfiguration100 .AdminServiceSpecificElement }
     *     
     */
    public TAdminServiceConfiguration100 .AdminServiceSpecificElement getAdminServiceSpecificElement() {
        return adminServiceSpecificElement;
    }

    /**
     * Sets the value of the adminServiceSpecificElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdminServiceConfiguration100 .AdminServiceSpecificElement }
     *     
     */
    public void setAdminServiceSpecificElement(TAdminServiceConfiguration100 .AdminServiceSpecificElement value) {
        this.adminServiceSpecificElement = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="admin_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AdminServiceSpecificElement {

        @XmlAttribute(name = "admin_type", required = true)
        protected String adminType;

        /**
         * Gets the value of the adminType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdminType() {
            return adminType;
        }

        /**
         * Sets the value of the adminType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdminType(String value) {
            this.adminType = value;
        }

    }

}
